viajanet/viajanet/Models/Compra.cs
namespace viajanet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Compra")]
    public partial class Compra
    {
        public int Id { get; set; }

        [Required]
        [StringLength(128)]
        public string Fk_Usuario { get; set; }

        public int FK_Viajem { get; set; }

        public int? FK_Hotel { get; set; }

        public int? Qtd_Adultos { get; set; }

        public int? Qtd_Criancas { get; set; }

        public double Valor_Total { get; set; }
        public string NumeroCartao { get; set; }
        public string NomeTitular { get; set; }
        public string Expiracao { get; set; }
        public string CVC { get; set; }
        public virtual Hotel Hotel { get; set; }

        public virtual Viajem Viajem { get; set; }
    }
}

viajanet/viajanet/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using viajanet.Models;

namespace viajanet.Controllers
{
    public class ComprasController : Controller
    {
        private ViajanetContext db = new ViajanetContext();

        // get  método que receberá a id da viagem que o usuário selecionou e pegará os hoteis da cidade da viagem pra exibir
       
        public ActionResult hospedagemHoteis()
        {
            int idCidadeViagem = Convert.ToInt32(Request["cidade"]);
            int id = Convert.ToInt32(Request["viagem"]);

            TempData["idViagem"] = id;

            var hoteis = db.Hotel.Include(h => h.Cidade).Include(h => h.Estado).Where(h => h.FK_Cidade == idCidadeViagem);
            
            return View(hoteis.ToList());
        }

        // método que irá conferir se o usuário deseja a hospedagem 

        public ActionResult confirmHospedagem()
        {
            if (!string.IsNullOrEmpty(Request["hotel"]) || !string.IsNullOrEmpty(Request["viagem"])) // isso me fará saber se o usuário reservou hotel ou não
            {
                var idHotel = Convert.ToInt32(Request["hotel"]);
                var idViajem = Convert.ToInt32(Request["viagem"]);

                
                ViewBag.Viajem = db.Viajem.Find(idViajem);
                var cidade = ViewBag.Viajem.Cidade;
                ViewBag.Hotel = db.Hotel.Find(idHotel);

            }
            else
            {
                if (!string.IsNullOrEmpty(Request["viagem"]))
                {
                    var idViagem = Convert.ToInt32(Request["viagem"]);
                    ViewBag.Viagem = db.Viajem.Find(idViagem);
                }
            }
            return View();
        }



        // GET: Compras
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            var compra = db.Compra.Include(c => c.Hotel).Include(c => c.Viajem);
            return View(await compra.ToListAsync());
        }

        // GET: Compras/Details/5
        
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compra compra = await db.Compra.FindAsync(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        // GET: Compras/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.FK_Hotel = new SelectList(db.Hotel, "Id", "Nome");
            ViewBag.FK_Viajem = new SelectList(db.Viajem, "Id", "Id");
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Fk_Usuario,FK_Viajem,FK_Hotel,Qtd_Adultos,Qtd_Criancas,Valor_Total")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                db.Compra.Add(compra);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.FK_Hotel = new SelectList(db.Hotel, "Id", "Nome", compra.FK_Hotel);
            ViewBag.FK_Viajem = new SelectList(db.Viajem, "Id", "Id", compra.FK_Viajem);
            return View(compra);
        }
        [Authorize(Roles = "Admin")]
        // GET: Compras/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compra compra = await db.Compra.FindAsync(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_Hotel = new SelectList(db.Hotel, "Id", "Nome", compra.FK_Hotel);
            ViewBag.FK_Viajem = new SelectList(db.Viajem, "Id", "Id", compra.FK_Viajem);
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Fk_Usuario,FK_Viajem,FK_Hotel,Qtd_Adultos,Qtd_Criancas,Valor_Total")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                db.Entry(compra).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.FK_Hotel = new SelectList(db.Hotel, "Id", "Nome", compra.FK_Hotel);
            ViewBag.FK_Viajem = new SelectList(db.Viajem, "Id", "Id", compra.FK_Viajem);
            return View(compra);
        }
        [Authorize(Roles = "Admin")]
        // GET: Compras/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compra compra = await db.Compra.FindAsync(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Compra compra = await db.Compra.FindAsync(id);
            db.Compra.Remove(compra);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: /Create
        [HttpPost]
        public ActionResult confirmCompra([Bind(Include = "Id,Fk_Usuario,FK_Viajem,FK_Hotel,Qtd_Adultos,Qtd_Criancas,Valor_Total,NomeTitular,CVC,Expiracao,NumeroCartao")] FormCollection collection)
        {
            try
            {
                Compra compra = new Compra();  
                compra.Fk_Usuario = collection["Fk_Usuario"];
                compra.FK_Viajem = Convert.ToInt32(collection["FK_Viajem"]);
                if (!string.IsNullOrEmpty(collection["FK_Hotel"])) { // aqui eu vejo se está nulo pois eu não sei se o usuário quiz algum hotel
                    compra.FK_Hotel = Convert.ToInt32(collection["FK_Hotel"]);
                }
                compra.Qtd_Adultos = Convert.ToInt32(collection["Qtd_Adultos"]);
                compra.Qtd_Criancas = Convert.ToInt32(collection["Qtd_Criancas"]);
                compra.Valor_Total = Convert.ToDouble(collection["Valor_Total"]);
                compra.NomeTitular = collection["name"];
                compra.NumeroCartao = collection["number"];
                compra.Expiracao = collection["expiry"];
                compra.CVC = collection["cvc"];
                db.Compra.Add(compra);
                db.SaveChanges();
                TempData["Compra"] = "Compra realizada com sucesso!";
                return RedirectToAction("procurarViajens","Viajens");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult viewCompras()
        {
            try
            {
                if (!string.IsNullOrEmpty(Request["user"]))
                {
                    string id = Request["user"];
                    var compras = db.Compra.Include(c => c.Hotel).Include(c => c.Viajem).Where(c => c.Fk_Usuario == id);
                    return View(compras.ToList());
                }
            }catch(Exception e)
            {
                TempData["Mensagem"] = "Ocorreu um erro ao tentar listar suas compras , erro:";
                TempData["tipo"] = "error";
                TempData["Erro"] = e.GetType().Name;
                RedirectToAction("procurarViajens", "Viajens");
            }
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

viajanet/viajanet/Views/Compras/Create.cshtml
@model viajanet.Models.Compra

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Compra</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fk_Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fk_Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fk_Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Viajem, "FK_Viajem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FK_Viajem", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FK_Viajem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Hotel, "FK_Hotel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FK_Hotel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FK_Hotel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd_Adultos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd_Adultos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd_Adultos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd_Criancas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd_Criancas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd_Criancas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor_Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor_Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor_Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroCartao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroCartao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroCartao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomeTitular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeTitular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeTitular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Expiracao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expiracao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Expiracao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CVC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CVC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CVC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

viajanet/viajanet/Views/Compras/Delete.cshtml
@model viajanet.Models.Compra

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Compra</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hotel.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hotel.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Viajem.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Viajem.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fk_Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fk_Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qtd_Adultos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qtd_Adultos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qtd_Criancas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qtd_Criancas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor_Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor_Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

viajanet/viajanet/Views/Compras/Details.cshtml
@model viajanet.Models.Compra

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Detalhes sobre sua viagem</h3>
    </div>
    <div id="dados" class="panel-body">
        <h4 class="">Viagem</h4>
        <div class="row">
            <div class="col-md-4">
               
                <dl>
                    <dt>De</dt>
                    <dd>@Model.Viajem.Cidade1.Nome</dd>
                    <dt>Data de embarque</dt>
                    <dd>@Model.Viajem.Data_Ida.ToShortDateString()</dd>
                   
                </dl>

            </div>
            <div class="col-md-4">
                <dl>
                    <dt>Para</dt>
                    <dd>@Model.Viajem.Cidade.Nome</dd>
                    <dt>Data de Retorno</dt>
                    <dd>@Model.Viajem.Data_Volta.ToShortDateString()</dd>
                  
                </dl>
            </div>
            <div class="col-md-4">
                <dl>
                    <dt>Quantidade de Adultos</dt>
                    <dd>@Model.Qtd_Adultos</dd>
                    <dt>Quantidade de Crianças</dt>
                    <dd>@Model.Qtd_Criancas</dd>
                    
                    <dt>Valor Total</dt>
                    <dd>R$ @Model.Valor_Total</dd>
                </dl>
            </div>
            <dl>

            </dl>
        </div>
        @if (Model.FK_Hotel != null)
        {
            <hr />
            <h4>Hotel</h4>
            <div class="row">
                <div class="col-md-6">
                    <dl>
                        <dt>Nome</dt>
                        <dd>@Model.Hotel.Nome</dd>
                        <dt>Telefone</dt>
                        <dd>@Model.Hotel.Telefone</dd>
                        <dt>Localização</dt>
                        <dd>@Model.Hotel.Longradouro , @Model.Hotel.Bairro</dd>
                    </dl>
                </div>
                
            </div>
        }
        <div class="row">
            <div class="col-md-12">
                <h4>Pagamento</h4>
                <dl>
                    <dt>Titular do cartão</dt>
                    <dd>@Model.NomeTitular</dd>
                    <dt>Numero do Cartão</dt>
                    <dd>@Model.NumeroCartao</dd>

                </dl>
            </div>
        </div>
        
    </div>
    <div class="panel-footer">
        <button id="imprimir" onclick="printContent('dados')" class="btn btn-default pull-right">Imprimir <i class="fa fa-print"></i></button>
    </div>
</div>




<script>
function printContent(el){
	var restorepage = document.body.innerHTML;
	var printcontent = document.getElementById(el).innerHTML;
	document.body.innerHTML = printcontent;
	window.print();
	document.body.innerHTML = restorepage;
}
</script>

viajanet/viajanet/Views/Compras/Edit.cshtml
@model viajanet.Models.Compra

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Compra</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Fk_Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fk_Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fk_Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Viajem, "FK_Viajem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FK_Viajem", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FK_Viajem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Hotel, "FK_Hotel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FK_Hotel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FK_Hotel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd_Adultos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd_Adultos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd_Adultos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd_Criancas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd_Criancas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd_Criancas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor_Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor_Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor_Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

viajanet/viajanet/Views/Compras/Index.cshtml
@model IEnumerable<viajanet.Models.Compra>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Hotel.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Viajem.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fk_Usuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qtd_Adultos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qtd_Criancas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor_Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroCartao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeTitular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Expiracao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CVC)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Hotel.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Viajem.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fk_Usuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Qtd_Adultos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Qtd_Criancas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Valor_Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumeroCartao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeTitular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Expiracao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CVC)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

viajanet/viajanet/Views/Compras/hospedagemHoteis.cshtml
@model IEnumerable<viajanet.Models.Hotel>

@{
    ViewBag.Title = "Hoteis";
}

<h2>Selecione o Hotel para hospedagem (Se disponível)</h2>
<div class="row">
    <div class="col-md-12">
        <a href="@Url.Action("confirmHospedagem","Compras", new {viagem = TempData.Peek("idViagem") })" class="btn btn-info pull-right"><span>Não desejo hospedagem / Não há Hoteis disponíveis</span></a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="store">
            @foreach (var item in Model)
{
            <div class="box">
                <div class="row">
                    <div class="col-sm-4">
                        @if (string.IsNullOrEmpty(item.Img))
                        {
                            <img src="~/Content/assets/img/imagem-nao-disponivel.png" class="mb20 img-responsive img-thumbnail">
                        }
                        else
                        {
                            <img src="~/Imagens/Hoteis/@item.Img" class="mb20 img-responsive img-thumbnail">
                        }
                        
                    </div>

                    <div class="col-sm-8">
                        <h3 class="product-title mt0 mb10"><a href="#">@Html.DisplayFor(modelItem => item.Nome)</a></h3>
                        <dl>

                            <dt>
                                @Html.DisplayNameFor(model => model.Telefone)
                            </dt>
                            <dd>
                                @Html.DisplayFor(modelItem => item.Telefone)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Longradouro)
                            </dt>
                            <dd>
                                @Html.DisplayFor(modelItem => item.Longradouro)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Cidade.Nome)
                            </dt>
                            <dd>
                                @Html.DisplayFor(modelItem => item.Cidade.Nome)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Bairro)
                            </dt>
                            <dd>
                                @Html.DisplayFor(modelItem => item.Bairro)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Cep)
                            </dt>
                            <dd>
                                @Html.DisplayFor(modelItem => item.Cep)
                            </dd>
                        </dl>
                    </div>
                </div>
                <div class="product-footer clearfix">
                    <div class="pull-right">
                        <a href="@Url.Action("confirmHospedagem","Compras",new { hotel = item.Id , viagem = @TempData.Peek("idViagem") })" class="add-to-cart btn btn-success pull-right"><i class="fa fa-bed"></i>&nbsp;<span class="hidden-xs">Reservar hospedagem</span></a>
                    </div>
                </div>
            </div>
}
        </div>
    </div>
</div>

viajanet/viajanet/Views/Compras/viewCompras.cshtml
@model IEnumerable<viajanet.Models.Compra>

@{
    ViewBag.Title = "viewCompras";
}

<h2>Minhas Compras</h2>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>Compras</h2>
                <div class="panel-ctrls">
                </div>
            </div>
            <div class="panel-body panel-no-padding">
                <table id="example" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            
                            <th>
                                De
                            </th>
                            <th>
                                Para
                            </th>
                            <th>
                                Data Ida
                            </th>
                            <th>
                                Data Volta
                            </th>
                            <th>
                                Quantidade de Adultos
                            </th>
                            <th>
                                Quantidade de Crianças
                            </th>
                            <th>
                                Valor Total
                            </th>
                            
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Viajem.Cidade1.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Viajem.Cidade.Nome)
                            </td>
                            <td>
                                    @item.Viajem.Data_Ida.ToShortDateString()
                            </td>
                            <td>
                                  @item.Viajem.Data_Volta.ToShortDateString()
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Qtd_Adultos)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Qtd_Criancas)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Valor_Total)
                            </td>
                           
                            <td>
                                @Html.ActionLink("Detalhes", "Details", new { id = item.Id },new {@class = "btn btn-info btn-block" }) 
                            </td>
                        </tr>
                    }
                        </tbody>

                </table>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>