viajanet/viajanet/Controllers/ViajensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using viajanet.Models;
using System.Text;
namespace viajanet.Controllers
{
    public class ViajensController : Controller
    {
        private ViajanetContext db = new ViajanetContext();

        // GET: Viajens
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            var viajem = db.Viajem.Include(v => v.Cidade).Include(v => v.Cidade1).Include(v => v.Companhia).Include(v => v.Estado).Include(v => v.Estado1);
            return View(await viajem.ToListAsync());
        }

        // GET: Viajens/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Viajem viajem = await db.Viajem.FindAsync(id);
            if (viajem == null)
            {
                return HttpNotFound();
            }
            return View(viajem);
        }

        // GET: Viajens/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.FK_Cidade_Destino = new SelectList(db.Cidade, "Id", "Nome");
            ViewBag.FK_Cidade_Saida = new SelectList(db.Cidade, "Id", "Nome");
            ViewBag.FK_Companhia = new SelectList(db.Companhia, "Id", "Nome");
            ViewBag.FK_Estado_Saida = new SelectList(db.Estado, "Id", "Nome");
            ViewBag.FK_Estado_Destino = new SelectList(db.Estado, "Id", "Nome");
            return View();
        }

        // POST: Viajens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,FK_Estado_Saida,FK_Cidade_Saida,FK_Estado_Destino,FK_Cidade_Destino,Valor,Data_Ida,Data_Volta,FK_Companhia")] Viajem viajem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Viajem.Add(viajem);
                    await db.SaveChangesAsync();
                    TempData["Mensagem"] = "Viajem cadastrada com sucesso!";
                    TempData["tipo"] = "success";
                    return RedirectToAction("Index");
                }


            }
            catch (Exception e)
            {
                TempData["Mensagem"] = "Ocorreu um erro ao cadastrar esta viajem erro:";
                TempData["tipo"] = "error";
                TempData["Erro"] = e.GetType().Name;
                return RedirectToAction("Index");
            }
           
            ViewBag.FK_Cidade_Destino = new SelectList(db.Cidade, "Id", "Nome", viajem.FK_Cidade_Destino);
            ViewBag.FK_Cidade_Saida = new SelectList(db.Cidade, "Id", "Nome", viajem.FK_Cidade_Saida);
            ViewBag.FK_Companhia = new SelectList(db.Companhia, "Id", "Nome", viajem.FK_Companhia);
            ViewBag.FK_Estado_Saida = new SelectList(db.Estado, "Id", "Nome", viajem.FK_Estado_Saida);
            ViewBag.FK_Estado_Destino = new SelectList(db.Estado, "Id", "Nome", viajem.FK_Estado_Destino);
            return View(viajem);
        }
       
        public ActionResult obterEstados()
        {
            var estados = db.Estado.ToList();
            StringBuilder options = new StringBuilder();
            options.Append("<option value=''> Selecione um estado </option>");
            foreach (var estado in estados)
            {
                options.Append("<option value='" + estado.Id + "'>" + estado.Nome + "</option>");
            }
            return Content(options.ToString());
        }

        [HttpPost]
        public ActionResult obterCidades()
        {
            int idEstado = Convert.ToInt32(Request["id"]);
            var cidades = db.Cidade.Where(c => c.FK_Estado == idEstado).ToList();
            StringBuilder options = new StringBuilder();
            options.Append("<option value='' selected> Selecione a cidade </option>");
            foreach(var cidade in cidades)
            {
                options.Append("<option value='" + cidade.Id + "'>" + cidade.Nome + "</option>");
            }
            return Content(options.ToString());
        }

        // GET: Viajens/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Viajem viajem = await db.Viajem.FindAsync(id);
            if (viajem == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_Cidade_Destino = new SelectList(db.Cidade, "Id", "Nome", viajem.FK_Cidade_Destino);
            ViewBag.FK_Cidade_Saida = new SelectList(db.Cidade, "Id", "Nome", viajem.FK_Cidade_Saida);
            ViewBag.FK_Companhia = new SelectList(db.Companhia, "Id", "Nome", viajem.FK_Companhia);
            ViewBag.FK_Estado_Saida = new SelectList(db.Estado, "Id", "Nome", viajem.FK_Estado_Saida);
            ViewBag.FK_Estado_Destino = new SelectList(db.Estado, "Id", "Nome", viajem.FK_Estado_Destino);
            return View(viajem);
        }

        // POST: Viajens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,FK_Estado_Saida,FK_Cidade_Saida,FK_Estado_Destino,FK_Cidade_Destino,Valor,Data_Ida,Data_Volta,FK_Companhia")] Viajem viajem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(viajem).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    TempData["Mensagem"] = "Edições realizadas comm sucesso!";
                    TempData["tipo"] = "success";
                    return RedirectToAction("Index");
                }

            }
            catch (Exception e)
            {
                TempData["Mensagem"] = "Ocorreu um erro ao editar esta viajem , erro:";
                TempData["tipo"] = "error";
                TempData["Erro"] = e.GetType().Name;
                return RedirectToAction("Index");
            }
            
            ViewBag.FK_Cidade_Destino = new SelectList(db.Cidade, "Id", "Nome", viajem.FK_Cidade_Destino);
            ViewBag.FK_Cidade_Saida = new SelectList(db.Cidade, "Id", "Nome", viajem.FK_Cidade_Saida);
            ViewBag.FK_Companhia = new SelectList(db.Companhia, "Id", "Nome", viajem.FK_Companhia);
            ViewBag.FK_Estado_Saida = new SelectList(db.Estado, "Id", "Nome", viajem.FK_Estado_Saida);
            ViewBag.FK_Estado_Destino = new SelectList(db.Estado, "Id", "Nome", viajem.FK_Estado_Destino);
            return View(viajem);
        }

        // GET: Viajens/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Viajem viajem = await db.Viajem.FindAsync(id);
            if (viajem == null)
            {
                return HttpNotFound();
            }
            return View(viajem);
        }

        // POST: Viajens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try {
                Viajem viajem = await db.Viajem.FindAsync(id);
                db.Viajem.Remove(viajem);
                await db.SaveChangesAsync();

                TempData["Mensagem"] = "Viajem deletada";
                TempData["tipo"] = "success";
               
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["Mensagem"] = "Ocorreu um erro ao deletar esta viajem , provavelmente ele está associado a alguma compra, caso não seja, contate o administrador e informe o seguinte erro:";
                TempData["tipo"] = "error";
                TempData["Erro"] = e.GetType().Name;
                return RedirectToAction("Index");
            }
        }

        //Get
        public ActionResult procurarViajens() {

            
            return View();
        }
        [HttpPost]
        public ActionResult resultViajens(FormCollection result) {

            var Csaida = Convert.ToInt32(result["CidadeSaida"]); // eu só preciso das Id's da cidade pra fazer a pesquisa
            var Cdestino = Convert.ToInt32(result["CidadeDestino"]);
            try
            {
                var viajens = db.Viajem.Include(v => v.Cidade).Include(v => v.Cidade1).Include(v => v.Companhia).Include(v => v.Estado).Include(v => v.Estado1).Where(v => v.FK_Cidade_Saida == Csaida).Where(v => v.FK_Cidade_Destino == Cdestino);
                return View(viajens.ToList());

            }
            catch (Exception e)
            {
                TempData["Mensagem"] = "Ocorreu um erro ao caregar as viajens , erro:";
                TempData["tipo"] = "error";
                TempData["Erro"] = e.GetType().Name;
                return RedirectToAction("procurarViajens");
            }
        } 

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

viajanet/viajanet/Views/Viajens/Delete.cshtml
@model viajanet.Models.Viajem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="form-horizontal">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="text-center">Você realmente deseja apagar esta viajem?</h3>
                            <p class="text-center">Obs: caso algum pacote esteja associado a esta viajem a ação não será conluída.</p>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <dl class="dl-horizontal">
                                <dt>
                                    De
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Cidade1.Nome)
                                </dd>
                                <dt>
                                    Companhia aérea
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Companhia.Nome)
                                </dd>
                                <dt>
                                    Data de Ida
                                </dt>

                                <dd>
                                    @Model.Data_Ida.ToShortDateString()
                                </dd>
                            </dl>
                        </div>
                        <div class="col-md-6">
                            <dl class="dl-horizontal">
                                <dt>
                                    Para
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Cidade.Nome)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Valor)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Valor)
                                </dd>
                                <dt>
                                    Data de volta
                                </dt>

                                <dd>
                                    @Model.Data_Volta.ToShortDateString()
                                </dd>
                            </dl>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-12">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-actions">
                                        <input type="submit" value="Apagar" class="btn btn-danger pull-right" />
                                        @Html.ActionLink("Voltar", "Index", "Viajens", new { @class = "btn btn-warning pull-left" })
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

viajanet/viajanet/Views/Viajens/Details.cshtml
@model viajanet.Models.Viajem

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Viajem</h4>
        <hr />
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        De
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cidade1.Nome)
                    </dd>
                    <dt>
                        Companhia aérea
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Companhia.Nome)
                    </dd>
                    <dt>
                        Data de Ida
                    </dt>

                    <dd>
                        @Model.Data_Ida.ToShortDateString()
                    </dd>
                </dl>
            </div>
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        Para
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cidade.Nome)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Valor)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Valor)
                    </dd>
                    <dt>
                        Data de volta
                    </dt>

                    <dd>
                        @Model.Data_Volta.ToShortDateString()
                    </dd>
                </dl>
            </div>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Editar dados", "Edit", new { id = Model.Id },new {@class = "btn btn-info pull-right" }) 
            @Html.ActionLink("Voltar", "Index","Viajens", new {@class = "btn btn-warning pull-left" })
        </div>
    </div>
</div>

viajanet/viajanet/Views/Viajens/Index.cshtml
@model IEnumerable<viajanet.Models.Viajem>

@{
    ViewBag.Title = "Index";
}

<h2>Visualização</h2>

<p>
    
    <a class="btn btn-success" href="@Url.Action("Create","Viajens")"><span><i class="glyphicon glyphicon-plus"></i> Novo</span></a>
</p>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>Viajens</h2>
                <div class="panel-ctrls">
                </div>
            </div>
            <div class="panel-body panel-no-padding ">
                <table id="example" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>
                                Estado de saída
                            </th>
                            <th>
                                Cidade saida
                            </th>
                            <th>
                                Estado de destino
                            </th>
                            <th>
                                Cidade destino
                            </th>
                            <th>
                                Companhia aérea
                            </th>
                            <th>
                                Data de ida
                            </th>
                            <th>
                                Data de Volta
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Valor)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estado.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cidade1.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estado1.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cidade.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Companhia.Nome)
                                </td>
                                
                                <td>
                                    @item.Data_Ida.ToShortDateString()
                                </td>
                                <td>
                                    @item.Data_Volta.ToShortDateString()
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Valor)
                                </td>
                                <td style="white-space: nowrap;">
                                    <a href="@Url.Action("Edit",new { id = item.Id })" class="btn btn-warning" title="Editar" data-toggle="tooltip"><span><i class="fa fa-pencil"></i></span></a>

                                    <a href="@Url.Action("Details",new { id = item.Id })" class="btn btn-info" title="Detalhes da viagem" data-toggle="tooltip"><span><i class="fa fa-list"></i></span></a>

                                    <a href="@Url.Action("Delete",new { id = item.Id })" class="btn btn-danger" title="Apagar viajem" data-toggle="tooltip"><span><i class=" fa fa-trash"></i></span></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

viajanet/viajanet/Views/Viajens/procurarViajens.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Pesquisa";

}
<h2>Pesquisa</h2>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("resultViajens", "Viajens", FormMethod.Post))
            {
            <div class="panel">
                <div class="panel-heading">
                    @Html.AntiForgeryToken()
                    <p>Para onde você quer ir? - @User.Identity.GetUserName()</p>
                </div>
                <div class="panel-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col-md-6">
                                <fieldset>
                                    <legend>Saída</legend>
                                    <div class="form-group">
                                        <div class="col-xs-12">
                                            <label for="estados-saida">Estado </label>
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-map-marker"></i>
                                                </span>
                                                <select id="estados-saida" name="EstadoSaida" class="form-control" data-live-search="true"></select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-xs-12">
                                            <label for="cidades-saida">Cidade </label>
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-map-marker"></i>
                                                </span>
                                                <select id="cidades-saida" name="CidadeSaida" class="form-control" data-live-search="true" title="Selecione"></select>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-md-6">
                                <fieldset>
                                    <legend>Destino</legend>
                                    <div class="form-group">
                                        <div class="col-xs-12">
                                            <label for="estados-destino">Estado </label>
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-map-marker"></i>
                                                </span>
                                                <select id="estados-destino" name="EstadoDestino" class="form-control" data-live-search="true"></select>
                                            </div>


                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-xs-12">
                                            <label for="cidades-destino">Cidade </label>
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-map-marker"></i>
                                                </span>
                                                <select id="cidades-destino" name="CidadeDestino" class="form-control" data-live-search="true"></select>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="form-group">
                        <button type="submit" class="btn btn-info pull-right"><span>Procurar <i class="glyphicon glyphicon-search"></i></span></button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
            $(document).ready(function () {
                
                estAtual = $("#estados-saida").val(); // como será feito assim que a p´gaina carregar os valores serão os mesmos para ambos os combos, então basta eu pegar o valor de 1

                $("#cidades-saida,#cidades-destino").empty();

                $.ajax({
                    type: "Post",
                    url: "/Viajens/obterEstados/",
                    success: function (data) {
                        $("#estados-saida,#estados-destino").append(data);
                        $("#cidades-saida,#cidades-destino").empty();
                        $("#cidades-saida,#cidades-destino").prepend("<option value='' selected>Selecione o Estado </option>");

                        // para o plugin funcionar corretamente eu tenho que inicializa-lo aqui
                        $("#estados-saida,#estados-destino").addClass("selectpickerEstados");
                        $('.selectpickerEstados').selectpicker();
                    }
                });

            })
            $(document).ready(function () {




                $("#estados-saida").change(function () {
                    estAtual = $("#estados-saida").val();
                    if (estAtual != "") {
                        $("#cidades-saida").empty();

                        $.ajax({
                            type: "Post",
                            url: "/Viajens/obterCidades/",
                            data: { "id": estAtual },
                            datatype: "Json",
                            success: function (data) {
                                $("#cidades-saida").append(data);
                                //$("#cidades-saida").removeClass("selectpickerCidadesSaida");
                                //$("#cidades-saida").addClass("selectpickerCidadesSaida");
                                //$(".selectpickerCidadesSaida").selectpicker();
                            }
                        });
                    } else {
                        $("#cidades-saida").empty();
                        $("#cidades-saida").prepend("<option value='' selected >Selecione o Estado </option>");
                    }

                });

                $("#estados-destino").change(function () {

                    estAtual = $("#estados-destino").val();
                    if (estAtual != "") {
                        $("#cidades-destino").empty();

                        $.ajax({
                            type: "Post",
                            url: "/Viajens/obterCidades/",
                            data: { "id": estAtual },
                            datatype: "Json",
                            success: function (data) {
                                $("#cidades-destino").append(data);
                                //$("#cidades-destino").addClass("selectpickerCidadesDestino");
                                //$(".selectpickerCidadesDestino").selectpicker();
                            }
                        });
                    } else {
                        $("#cidades-destino").empty();
                        $("#cidades-destino").prepend("<option value='' selected >Selecione o Estado </option>");
                    }

                });

            });


    </script>
}