viajanet/viajanet/Models/Hotel.cs
namespace viajanet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Hotel")]
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            Compra = new HashSet<Compra>();
            Quarto = new HashSet<Quarto>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(150)]
        public string Nome { get; set; }

        [Required]
        [StringLength(50)]
        public string Telefone { get; set; }

        [Required]
        [StringLength(150)]
        public string Longradouro { get; set; }

        public int FK_Estado { get; set; }

        public int FK_Cidade { get; set; }

        [Required]
        [StringLength(50)]
        public string Bairro { get; set; }

        [Required]
        [StringLength(50)]
        public string Cep { get; set; }

        [StringLength(250)]
        public string Img { get; set; }

        public virtual Cidade Cidade { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }

        public virtual Estado Estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quarto> Quarto { get; set; }
    }
}

viajanet/viajanet/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using viajanet.Models;
using System.Text;
using System.IO;

namespace viajanet.Controllers
{
    public class HotelsController : Controller
    {
        private ViajanetContext db = new ViajanetContext();

        // GET: Hotels
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            var hotel = db.Hotel.Include(h => h.Cidade).Include(h => h.Estado);
            return View(await hotel.ToListAsync());
        }

        // GET: Hotels/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = await db.Hotel.FindAsync(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // GET: Hotels/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.FK_Cidade = new SelectList(db.Cidade, "Id", "Nome");
            ViewBag.FK_Estado = new SelectList(db.Estado, "Id", "Nome");
            return View();
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Nome,Telefone,Longradouro,FK_Estado,FK_Cidade,Bairro,Cep,Img")] Hotel hotel,HttpPostedFileBase img)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    if (img != null)
                    {
                        FileInfo imgInfo = new FileInfo(img.FileName);

                        if (imgInfo.Extension.Equals(".jpg", StringComparison.InvariantCultureIgnoreCase) || imgInfo.Extension.Equals(".png", StringComparison.InvariantCultureIgnoreCase) || imgInfo.Extension.Equals(".gif", StringComparison.InvariantCultureIgnoreCase))
                        {
                            string imgNome = Guid.NewGuid().ToString("N") + imgInfo.Extension.ToLower();
                            img.SaveAs(Server.MapPath("~/Imagens/Hoteis/" + imgNome));
                            hotel.Img = imgNome;
                        }

                        //System.IO.Directory.CreateDirectory(HttpContext.Server.MapPath("~/Imagens/Hoteis/") + hotel.Nome + "/" + hotel.Cep);
                        //img.SaveAs(HttpContext.Server.MapPath("~/Imagens/Hoteis/" + hotel.Nome + "/" + hotel.Cep + "/") + img.FileName);
                        //hotel.Img = "/Imagens/Hoteis/" + hotel.Nome + "/" + hotel.Cep + "/" + img.FileName;
                        //hotel.Img = hotel.Nome + "/" + hotel.Cep + "/" +  img.FileName;
                    }

                    db.Hotel.Add(hotel);
                    await db.SaveChangesAsync();
                    TempData["Mensagem"] = "Hotel Cadastrado com sucesso";
                    TempData["tipo"] = "success";
                    return RedirectToAction("Index");
                }
            }
            catch(Exception e)
            {
                TempData["Mensagem"] = "Ocorreu um erro ao cadastrar este hotel , erro:";
                TempData["tipo"] = "error";
                TempData["Erro"] = e.GetType().Name;
                return RedirectToAction("Index");
            }
            

            ViewBag.FK_Cidade = new SelectList(db.Cidade, "Id", "Nome", hotel.FK_Cidade);
            ViewBag.FK_Estado = new SelectList(db.Estado, "Id", "Nome", hotel.FK_Estado);
            return View(hotel);
        }
        //Post
        [HttpPost]
        public ActionResult obterCidades()
        {
            int id = Convert.ToInt32(Request["id"]);
            var cidades = db.Cidade.Where(c => c.FK_Estado == id);

            StringBuilder options = new StringBuilder();
            options.Append("<option value=''>Selecione sua cidade </option>");
            foreach (var cid in cidades)
            {
                options.Append("<option value='" + cid.Id + "'>" + cid.Nome + "</option>");
            }
            return Content(options.ToString());

        }
        // GET: Hotels/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = await db.Hotel.FindAsync(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_Cidade = new SelectList(db.Cidade, "Id", "Nome", hotel.FK_Cidade);
            ViewBag.FK_Estado = new SelectList(db.Estado, "Id", "Nome", hotel.FK_Estado);
            return View(hotel);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Nome,Telefone,Longradouro,FK_Estado,FK_Cidade,Bairro,Cep,Img")] Hotel hotel, HttpPostedFileBase img)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string nomeImagemAntiga = Request["imagemAntiga"];
                    if (img != null) // se o usuário quis outra imagem
                    {

                        FileInfo imgInfo = new FileInfo(img.FileName);

                        if (imgInfo.Extension.Equals(".jpg", StringComparison.InvariantCultureIgnoreCase) || imgInfo.Extension.Equals(".png", StringComparison.InvariantCultureIgnoreCase) || imgInfo.Extension.Equals(".gif", StringComparison.InvariantCultureIgnoreCase))
                        {
                            string imgNome = "";
                            if (nomeImagemAntiga != string.Empty) // pra saber se já existe uma imagem deste hotel
                            {
                                var caminhoImagem = Server.MapPath("~/Imagens/Hoteis/" + nomeImagemAntiga);
                                System.IO.File.Delete(caminhoImagem);
                            }
                            imgNome = Guid.NewGuid().ToString("N") + imgInfo.Extension.ToLower();
                            img.SaveAs(Server.MapPath("~/Imagens/Hoteis/" + imgNome));
                            hotel.Img = imgNome;
                        }
                    }
                    else // se a imagem for nula eu atribuo null ao meu objeto
                    {

                        hotel.Img = nomeImagemAntiga;

                    }

                    db.Entry(hotel).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    TempData["Mensagem"] = "Edições realizadas com succeso";
                    TempData["tipo"] = "success";
                    return RedirectToAction("Details", new { id = hotel.Id });

                }
            }
            catch(Exception e)
            {
                TempData["Mensagem"] = "Ocorreu um erro ao editar este hotel , erro:";
                TempData["tipo"] = "error";
                TempData["Erro"] = e.GetType().Name;
                return RedirectToAction("Index");
            }
            ViewBag.FK_Cidade = new SelectList(db.Cidade, "Id", "Nome", hotel.FK_Cidade);
            ViewBag.FK_Estado = new SelectList(db.Estado, "Id", "Nome", hotel.FK_Estado);
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = await db.Hotel.FindAsync(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try {
                
                Hotel hotel = await db.Hotel.FindAsync(id);
                if (hotel.Img != string.Empty) // pra saber se já existe uma imagem deste hotel
                {
                    var caminhoImagem = Server.MapPath("~/Imagens/Hoteis/" + hotel.Img);
                    System.IO.File.Delete(caminhoImagem);
                }
                db.Hotel.Remove(hotel);
                await db.SaveChangesAsync();
                TempData["Mensagem"] = "Hotel Deletado com sucesso";
                TempData["tipo"] = "success";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["Mensagem"] = "Ocorreu um erro ao deletar este hotel , provavelmente ele está associado a alguma compra.";
                TempData["tipo"] = "error";
                TempData["Erro"] = e.GetType().Name;
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

viajanet/viajanet/Views/Hotels/Create.cshtml
@model viajanet.Models.Hotel

@{
    ViewBag.Title = "Cadastro de Hoteis";
}
   	
<!-- Start loading page level scripts and css for this page -->
<link type="text/css" href="~/Content/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css" rel="stylesheet"> <!-- Touchspin -->
<link type="text/css" href="~/Content/assets/js/jqueryui.css" rel="stylesheet">        									<!-- jQuery UI CSS -->
<script type="text/javascript" src="~/Content/assets/plugins/form-jasnyupload/fileinput.min.js"></script>               			<!-- File Input -->										<!-- Card -->   							

<!-- End loading page level scripts-->
<h2>Cadastro</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        
        <div class="row">
            <div class="col-md-12">
                <h4>Hotel</h4>
                <hr />
            </div>
        </div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Create", "Hotels", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
           @Html.AntiForgeryToken()
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-xs-12">
                                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "sr-only" })
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class=" glyphicon glyphicon-list"></i>
                                    </span>
                                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome" } })
                                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "sr-only" })
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-phone"></i>
                                    </span>
                                    @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control phone", @placeholder = "Telefone" } })

                                    @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                @Html.LabelFor(model => model.Longradouro, htmlAttributes: new { @class = "sr-only" })
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-map-marker"></i>
                                    </span>
                                    @Html.EditorFor(model => model.Longradouro, new { htmlAttributes = new { @class = "form-control", @placeholder = "Longradouro(Rua,Avenida etc)" } })
                                    @Html.ValidationMessageFor(model => model.Longradouro, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                @Html.LabelFor(model => model.FK_Estado, "estado", htmlAttributes: new { @class = "control-label  sr-only" })
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-map-marker"></i>
                                    </span>
                                    @Html.DropDownList("FK_Estado", null, htmlAttributes: new { @class = "form-control", @id = "estados", @required = "required" })
                                    @Html.ValidationMessageFor(model => model.FK_Estado, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                <label for="Cidades" class="sr-only">Cidades</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-map-marker"></i>
                                    </span>
                                    <select id="cidades" name="FK_Cidade" class="form-control" required="required">
                                        <option value="">Selecione o Estado</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.FK_Cidade, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "sr-only" })
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-map-marker"></i>
                                    </span>
                                    @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control", @placeholder = "Bairro" } })
                                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "sr-only" })
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-map-marker"></i>
                                    </span>
                                    @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "form-control cep", @placeholder = "CEP" } })
                                    @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <div class="">
                            <div class="fileinput fileinput-new" style="width: 100%;" data-provides="fileinput">
                                <div class="fileinput-preview thumbnail mb20" data-trigger="fileinput" style="width: 100%; height: 150px;"></div>
                                <div>
                                    <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remover</a>
                                    <span class="btn btn-info btn-file"><span class="fileinput-new">Selecione uma imagem</span><span class="fileinput-exists">Mudar</span><input accept="image/*" type="file" name="Img"></span>
                                    <p class="help-block">Obs: Só aceitamos imagens do tipo .gif .png e .jpg</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div>
                                <input type="submit" value="Cadastrar" class="btn btn-success pull-right" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
    
    <script>
        $(document).ready(function () {
            // init masks
            var maskBehavior = function (val) {
                return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
            options = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(maskBehavior.apply({}, arguments), options);
                }
            };

            $('.phone').mask(maskBehavior, options);
            $('.cep').mask('00000-000');

            // end masks
            $("#estados").prepend("<option value='' selected >Selecione o Estado </option>");
            $("#estados").change(function () {

                estAtual = $("#estados").val();
                if (estAtual != "") {
                    $("#cidades").empty();

                    $.ajax({
                        type: "Post",
                        url: "/Hotels/obterCidades/",
                        data: { "id": estAtual },
                        datatype: "Json",
                        success: function (data) {
                            $("#cidades").append(data);
                        }
                    });
                } else {
                    $("#cidades").empty();
                    $("#cidades").prepend("<option value='' selected >Selecione o Estado </option>");
                }

        });
    });
</script> 
}

viajanet/viajanet/Views/Hotels/Details.cshtml
@model viajanet.Models.Hotel

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
                <h4 class="text-center">@Html.DisplayFor(model => model.Nome)</h4>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Estado.Nome)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Estado.Nome)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Cidade.Nome)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cidade.Nome)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Telefone)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Telefone)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Longradouro)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Longradouro)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Bairro)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Bairro)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Cep)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cep)
                    </dd>
                </dl>

            </div>
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dd>
                        @if (string.IsNullOrEmpty(Model.Img))
                        {
                            <img src="~/Content/assets/img/imagem-nao-disponivel.png" class="img-responsive img-thumbnail">
                        }
                        else
                        {
                            <img src="~/Imagens/Hoteis/@Model.Img" class="img-thumbnail" />
                        }
                        
                    </dd>
                </dl>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-warning pull-left" href="@Url.Action("Index","Hotels")"><span><i class="fa fa-arrow-left"></i> Voltar</span></a>
                    <a href="@Url.Action("Edit",new { id = Model.Id })" class="btn btn-info pull-right"><span><i class="fa fa-edit"></i> Editar dados</span></a>
                </div>
            </div>
        </div>
    </div>
</div>

viajanet/viajanet/Views/Hotels/Index.cshtml
@model IEnumerable<viajanet.Models.Hotel>

@{
    ViewBag.Title = "Visualização de Hoteis";
}

<h2>Visualização</h2>

<p>
    <a href="@Url.Action("Create","Hotels")" class="btn btn-success" title="Novo Hotel" data-toggle="tooltip"><span><i class="glyphicon glyphicon-plus"></i></span> Novo</a> 
</p>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>Hoteis</h2>
                <div class="panel-ctrls">
                </div>
            </div>
            <div class="panel-body panel-no-padding">
                <table id="example" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Nome)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Telefone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Longradouro)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado.Nome)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Cidade.Nome)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Bairro)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Cep)
                            </th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Telefone)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Longradouro)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estado.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cidade.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Bairro)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cep)
                                </td>
                                <td style="white-space: nowrap;" class="center-block">
                                    <a href="@Url.Action("viewQuartosHotel","Quartos",new { id = item.Id })" class="btn btn-success" title="Visualizar quartos" data-toggle="tooltip"><span><i class="fa fa-bed"></i></span></a>

                                    <a href="@Url.Action("Edit",new { id = item.Id })" class="btn btn-warning" title="Editar" data-toggle="tooltip"><span><i class="fa fa-pencil"></i></span></a>

                                    <a href="@Url.Action("Details",new { id = item.Id })" class="btn btn-info" title="Detalhes do hotel" data-toggle="tooltip"><span><i class="fa fa-list"></i></span></a>

                                    <a href="@Url.Action("Delete",new { id = item.Id })" class="btn btn-danger" title="Apagar Hotel" data-toggle="tooltip"><span><i class=" fa fa-trash"></i></span></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>